### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by midsoune** [BrunoSobrino/TheMystic-Bot-MD#82]
Translate to other languages

**Comment by BrunoSobrino** [comment]
Hi @MIDSOUNE 

We are working on improving all the commands and connection system of the Bot, as soon as we are sure that everything is already functional, we may make it multilanguage or make other repositories with the translated Bot. That does not have an estimated date since I am no longer aware of Bot issues, as indicated in the notice in the readme.. I am retired.

**Comment by Skidy89** [comment]
The creator responded, there is no need to have this issue open
